#!/bin/bash

BASEDIR=$(dirname $0)
cd ${BASEDIR}
source script_vars
PID_FILE="quest_web.pid"

case $1 in
   start)
      cd ${ENV_DIR}
      source bin/activate
      cd ${PROJECT_DIR}
      python web/root.py &
      cd "../.."
      echo $! > ${RUN_DIR}"/"${PID_FILE};
      ;;
    stop)
      cd ${ENV_DIR}
      kill `cat ${RUN_DIR}"/"${PID_FILE}` ;;
    *)
      echo "usage: web {start|stop}" ;;
esac
exit 0
